### ISSUE TITLE
show facsimile snippets on hover

### ISSUE THREAD

**Issue by cneud** [qurator-spk/neath#19]
it would be desirable to display the snippets in the left column upon hovering over their location (saves a lot of clicking)

**Comment by cneud** [comment]
added in c488b94fe37241deb4d0e10391694b222b70e86b

**Comment by snmnzl** [comment]
This is very helpful, but eliminated the view of the full page, which is important for questions of broader context in case of unrecognizable OCR. Can the full page be re-linked as the standard picture (right now the standard would be the snippet of line 0)? Also, is there any chance of getting a zoom of the snippet by clicking on the line?

**Comment by cneud** [comment]
@snmnzl Not really - if you click on the images snippets displayed on the leftmost column, a new tab will open with a larger contextual snippet of the according token. In our experience, this is preferable to the full page view, which is so large that it can be hard to identify the token in it. Have you seen this already?

Upscaling the snippet is sth we have to investigate.

**Comment by snmnzl** [comment]
@cneud I see - I think this is sufficient in case of context-problems. You are right about the full page view's size.

**Comment by cneud** [comment]
Perfect. We can also extend the context window size for the larger snippet that is opened in a new tab as required. 

Btw, this will generate a URL like ``http://content.staatsbibliothek-berlin.de/zefys/SNP27646518-18800101-0-3-0-0/124,333,278,82/full/0/default.jpg`` where ``...124,333,278,82`` are the pixel coordinates of the snippet. When replaced with ``full`` in the URL, this will always retrieve the full image in the browser, e.g. http://content.staatsbibliothek-berlin.de/zefys/SNP27646518-18800101-0-3-0-0/full/full/0/default.jpg.

Last but not least, unfortunately scaling up the images in the browser is not a decent solution - the upscaled images look horrible. The resolution we already show in the snippets is also already taken from the largest image we have here ourselves.

I will close this for now, but feel free to re-open or open a new issue if further needs arise for the facsimile display part of the tool.
