### ISSUE TITLE
support confirmation of OCR-changes by ENTER key

### ISSUE THREAD

**Issue by snmnzl** [qurator-spk/neath#24]
It would be practical, if pressing ENTER would confirm the current value in the token-line like clicking on OK.

**Comment by snmnzl** [comment]
Accordingly, cancellation by DELETE or ESC would be desireable.

**Comment by cneud** [comment]
DELETE is already used (actually BACKSPACE) so I suggest to go with ESC for cancellation?

**Comment by snmnzl** [comment]
> 
> 
> DELETE is already used within the token text correction (actually BACKSPACE) so I suggest to go with ESC for cancellation?

Works fine for us

**Comment by cneud** [comment]
added in ede687065e08b58ae9d6dbca601788560545ad63
