### ISSUE TITLE
reduce no. of lines

### ISSUE THREAD

**Issue by snmnzl** [qurator-spk/neath#27]
In the current version, there are 30 lines shown at a time which avoids a full view unless the browser screen is zoomed down to 60%. A reduction to appr. 15 lines combined with the aligned image snippet #26 would improve usability by a great deal.

**Comment by cneud** [comment]
set `DisplayRows`to `20` 7c89b012cb00a4a8d8bc7e64bba5fa76aa8fc430

**Comment by cneud** [comment]
I've set the number of rows to 20 now, which leaves a lot of dead space on my screen. Can you test again if this is going in the intended direction? What resolution are you working with?

**Comment by snmnzl** [comment]
I see - it differs for me, since I have a laptop screen and a docking screen. It does go in the intended direction and is far more usable already, yes. Generally, a responsive interface would be desireable. Alternatively, manual dynamic adaption would be an option (e.g. a filter to chose between 30, 20 and 10 lines on display). If non of this is feasible, please optimize for the student assistant's screen, which is 1536x864. I attach a sceenshot of the display on her screen in Firefox with the most current version. Atm, she zooms out to 80% in order to have full display.

![Neath Scrennshot 2](https://user-images.githubusercontent.com/56627609/69241706-92dec500-0b9f-11ea-81db-1c1d8ebfa542.PNG)

**Comment by cneud** [comment]
Wooo, 864px is not much. Unfortunately, for this use case, it will not be possible to make a fully responsive interface. I will set the display to 15 lines then, as it seems that will fit the student assistant's screen (counting 18 lines in the screenshot).

**Comment by cneud** [comment]
changed in 509eb9512c6e175e4d22c6df7ba4c0fbb648ce6d
