### ISSUE TITLE
support navigation by arrow keys in token-column

### ISSUE THREAD

**Issue by snmnzl** [qurator-spk/neath#28]
First testing sessions show that in case of OCR-correction, nearly every line needs to be altered. Therefore, navigation to the line above or below (up/down) without clicking would be crucial, including  #24 . Navigation within the string by left/right arrow key as in the current version is very helpful.

**Comment by snmnzl** [comment]
Additionally, would it be possible to lock the shown position for the selected line (meaning you can navigate through the 15 lines shown at a time, but the cursor stays in place in the middle of the scren, which would be the 7th line, while the lines move)?

**Comment by cneud** [comment]
Note to self: review http://dmauro.github.io/Keypress/ for this (thx @kba)

**Comment by cneud** [comment]
added in ede687065e08b58ae9d6dbca601788560545ad63

**Comment by snmnzl** [comment]
Thank you for the adjustment - combined with #24, this is really helpful. The navigation, however, only works within the string (left-right), not over the lines. Would this be possible aswell?

**Comment by labusch** [comment]
Can you provide an example file where this problem appears?

**Comment by snmnzl** [comment]
Nevermind, the navigation does indeed work - our mistake!

**Comment by labusch** [comment]
Ok, I pushed some little patch to make the edit area resizable again such that editing of longer tokens is more comfortable.
