### ISSUE TITLE
modification of sentence marks not possible

### ISSUE THREAD

**Issue by snmnzl** [qurator-spk/neath#36]
If the manual marking of a sentence is made by mistake, marking the actual beginning does not set off continuous counting of the lines.
![grafik](https://user-images.githubusercontent.com/56627609/70453515-30dff400-1aa9-11ea-875d-caaec1be4e22.png)

**Comment by cneud** [comment]
fixed by a1bd8afc9dd764c87c24992143632b9aa11b3d07
