### ISSUE TITLE
"Breslau" problem

### ISSUE THREAD

**Issue by snmnzl** [qurator-spk/neath#44]
A funny thing occured in our annotation sessions, both to the student assistant and me on different browsers (Firefox and Edge) when we try to correct the word "Breslau" in the file 27646518_1892-07-05_21_335_005 (occurs two times in the third newspaper-column of the document: line 4599 and line 4834):

After annotating for a while (different time spans) the page seems to "reload" but it looks more like a flicker than a reload.
The tags can not longer be accessed, the NERs can no longer be edited. By saving at this point and reopening the file, the facsimile snippet does no longer appear, even though saving and editing are possible (but useless without the snippet). This can be fixed by re-opening NEATH over and over until Snippet is visible again.

**Comment by cneud** [comment]
@snmnzl Thanks for reporting. This sounds weird, did this "reload" ever occur on other files? Btw it seems the filename ``27646518_1892-07-05_21_335_005`` is wrong as I cannot find any ``Breslau`` in that file?

**Comment by labusch** [comment]
Hi, thanks for the report!
I can reproduce it on my computer too!

**Comment by cneud** [comment]
There may be two issues at hand here - sometimes the IIIF server that delivers the snippet has the hiccups, which leads to the facsimile snippets not being displayed, but this should not normally affect the editing features of neath.

**Comment by snmnzl** [comment]
@labusch thanks for the feedback!
@cneud The local filename is 

> 27646518_1892-07-05_21_335_005.xml

> Breslau
does not occur, because the correct string was not recognized in both cases (lines 4599 and 4834). The problem occurs, as soon as we try to edit the string. It occurs independently from the letters we type.

**Comment by cneud** [comment]
Thx @snmnzl, now I found the two occurences (the line numbera differ in my unaltered file) and can also reproduce. We're looking into it.

**Comment by snmnzl** [comment]
@cneud Great, thank you! The line numbers are weird though, since I have used the unaltered file aswell. In neath, the ocurrence of `Uroutan` is line 4599 and in Excel, two lines should add up, because of the table header and .jpeg-Link, but it is three (line 4602). Same with `Beealan` (line 4834 in neath, 4837 in Excel).

**Comment by snmnzl** [comment]
Update: Problem occurs aswell in 27112366_1874-08-25_000_197_0_006.tsv (Vossische Zeitung vom 25.08.1874) in line no. 4170 (Excel), 4167 (neath). 
Still concerns the correction of the Word `Breslau` (OCR recognized `Rreslan`).

**Comment by snmnzl** [comment]
Another update: Problem occurs aswell concerning the word `Ueberlandspost` in 27112366_1874-08-25_000_197_0_006.tsv (Vossische Zeitung vom 25.08.1874) in line no. 4764 (Excel), 4785 (neath)
(OCR recognized `telanezreft`)

**Comment by labusch** [comment]
Thank you for the additional report.
That one finally lead me to the root of the problem.

Big price question: what are the similarities between "Breslau" and "Überlantspost"?

Well, BresLAu and ÜberLAntspost...

There is, as you already know, a key combination l + a the adds one additional table row.
The core of the bug is that this combination is not disabled while editing text (though the same problem appears with other key combinations too but has not been noticed so far).

I'll push a fix for that problem and all the other key combinations very soon.

**Comment by labusch** [comment]
Should be fixed now.

**Comment by snmnzl** [comment]
This is great, thx @labusch!

**Comment by cneud** [comment]
fixed in 2729bb35bad2d2d5fffcb5e7b213d63188d05ce4
