### ISSUE TITLE
add entity tag "TODO"

### ISSUE THREAD

**Issue by cneud** [qurator-spk/neath#7]
...for uncertain/yet to decide entity types

**Comment by cneud** [comment]
added in 6048fba43486820e23976703908dc99b51d278e6

**Comment by snmnzl** [comment]
I did not find the tag in the current version of the master-branch.

**Comment by cneud** [comment]
The ``*-TODO`` tag is still there, but was hidden in the accordion due to the new types that were added - we therefore increased the accordion size in the latest version. Can you check that you are using the most recent version and confirm?

**Comment by snmnzl** [comment]
Confirmed! The TODO tag indeed does show again - thanks!
